displayName: Add response header
summary: Plugin that copies request header value into a response header.
type: middleware
import: github.com/LumensGroup/add-trace-response-header
testData:
  from: X-Trace-Id
  to: X-Trace-Id
  overwrite: false
  regexp: "^(.*)$"
  replacement: "$1"
